//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _18
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public int commentID { get; set; }
        public string messageComments { get; set; }
        public Nullable<int> masterID { get; set; }
        public Nullable<int> requestID { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Requests Requests { get; set; }
    }
}
