USE [master]
GO

/****** Object:  Database [b1kolychevaDem]    Script Date: 07.12.2024 14:20:33 ******/
CREATE DATABASE [b1kolychevaDem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'b1kolychevaDem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.KOLYCHEVA\MSSQL\DATA\b1kolychevaDem.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'b1kolychevaDem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.KOLYCHEVA\MSSQL\DATA\b1kolychevaDem_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [b1kolychevaDem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [b1kolychevaDem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET ARITHABORT OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [b1kolychevaDem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [b1kolychevaDem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET  ENABLE_BROKER 
GO

ALTER DATABASE [b1kolychevaDem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [b1kolychevaDem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET RECOVERY FULL 
GO

ALTER DATABASE [b1kolychevaDem] SET  MULTI_USER 
GO

ALTER DATABASE [b1kolychevaDem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [b1kolychevaDem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [b1kolychevaDem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [b1kolychevaDem] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [b1kolychevaDem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [b1kolychevaDem] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [b1kolychevaDem] SET QUERY_STORE = ON
GO

ALTER DATABASE [b1kolychevaDem] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [b1kolychevaDem] SET  READ_WRITE 
GO


